// Copyright 2024 George Norton (@george-norton)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define DIGITIZER_MOTION_PIN GP28
#define DIGITIZER_MOTION_PIN_ACTIVE_LOW yes
#define MXT_SWITCH_XY
#define MXT_SENSOR_WIDTH_MM 91
#define MXT_SENSOR_HEIGHT_MM 156
#define I2C1_CLOCK_SPEED 1000000
#define RGBLIGHT_LIMIT_VAL 1
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 1
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
